include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - vendor/**
    - "**/*.g.dart"
  errors:
    always_declare_return_types: error
    await_only_futures: error
    directives_ordering: warning
    file_names: error
    prefer_final_fields: error
    prefer_relative_imports: warning
    prefer_single_quotes: error
    prefer_typing_uninitialized_variables: error
    unawaited_futures: warning
    unnecessary_parenthesis: error
    use_function_type_syntax_for_parameters: warning

  language:
    strict-raw-types: true
  plugins:
    # - dart_code_metrics
    - custom_lint


dart_code_metrics:
  anti-patterns:
    - long-method
    - long-parameter-list
  metrics:
    cyclomatic-complexity: 20
    maximum-nesting-level: 5
    number-of-parameters: 4
    source-lines-of-code: 50
  metrics-exclude:
    - test/**
  rules:
    - newline-before-return
    - no-boolean-literal-compare
    - no-empty-block
    - prefer-trailing-comma
    - prefer-conditional-expressions
    - no-equal-then-else

linter:
  rules:
    - always_declare_return_types
    - avoid_redundant_argument_values
    - avoid_void_async
    - await_only_futures
    - cast_nullable_to_non_nullable
    - directives_ordering
    - file_names
    - leading_newlines_in_multiline_strings
    - no_default_cases
    - omit_local_variable_types
    - parameter_assignments
    - prefer_const_constructors_in_immutables
    - prefer_final_fields
    - prefer_final_in_for_each
    - prefer_final_locals
    - prefer_foreach
    - prefer_generic_function_type_aliases
    - prefer_if_null_operators
    - prefer_interpolation_to_compose_strings
    - prefer_null_aware_operators
    - prefer_relative_imports
    - prefer_single_quotes
    - prefer_typing_uninitialized_variables
    - require_trailing_commas
    - sort_constructors_first
    - sort_pub_dependencies
    - sort_unnamed_constructors_first
    - unnecessary_brace_in_string_interps
    - unnecessary_getters_setters
    - unnecessary_lambdas
    - unnecessary_null_checks
    - unnecessary_nullable_for_final_variable_declarations
    - unnecessary_overrides
    - unnecessary_parenthesis
    - unnecessary_this
    - use_build_context_synchronously
    - use_function_type_syntax_for_parameters
    - use_late_for_private_fields_and_variables
    - use_named_constants
    - void_checks
