name: u2f
description: >
  FIDO Universal 2nd Factor.
  Register a FIDO2 U2F key to your application
  Verify a FIDO2 U2F key assertion
version: 2.0.0
homepage: 
repository: https://github.com/DavBfr/flutter_u2f
issue_tracker: https://github.com/DavBfr/flutter_u2f/issues
documentation: https://fidoalliance.org/specs/fido-u2f-v1.0-ps-20141009/fido-u2f-overview-ps-20141009.html
topics:
 - auth
 - fido
 - 2fa

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  async: ^2.8.2
  cbor: ^6.1.1
  crypto: ^3.0.2
  ffi: ^2.1.0
  flutter:
    sdk: flutter
  flutter_nfc_kit: ^3.3.1
  js: ^0.7.1
  logging: ^1.1.0
  plugin_platform_interface: ^2.1.0
  pointycastle: ^3.6.0
  web: ^0.5.1

dev_dependencies:
  ffigen:
  flutter_lints: ">=3.0.0"
  flutter_test:
    sdk: flutter

ffigen:
  name: "Api"
  output: "lib/generated_bindings.dart"
  compiler-opts:
    - "-Wno-nullability-completeness"
  functions:
    rename:
      "hid_(.*)": "$1"
  headers:
    entry-points:
      - "webauthn.h"
    include-directives:
      - "webauthn.h"

flutter:
  plugin:
    platforms:
      macos:
        ffiPlugin: true
      windows:
        ffiPlugin: true
